#!/bin/bash

if [ -z $1 ]; then
    echo "Count number of lines in a compressed text file."
    echo "Usage: zwcl file.txt.gz"
    echo "Output: Number of lines as shown by 'wc -l'"
else
    echo $1 `zcat $1 | wc -l`
fi
