#!/bin/bash

DELIM=$2

if [ -z $1 ]; then
    echo "Counts the number of columns from the first line of the file"
    echo "Usage: cols file.txt [delimiter]"
    echo "Output: number of columns"
else
    if [ -z $DELIM ]; then
        DELIM="\t"
    fi

    awk -F $DELIM 'NR==1 {print NF}' $1
fi
