#!/bin/bash
#
# Split a given string by a given delimiter

STRING=$1
DELIM=$2
USAGE="Usage: splitstr string delimiter"

if [ -z $STRING ] || [ -z $DELIM ]; then
    echo "Split a string into individual lines based on a user-supplied delimiter"
    echo $USAGE
    exit
fi

echo $STRING | sed "s/${DELIM}/\n/g"
